### ISSUE TITLE
Problema ao interpolar elemento dentro do innerHTML.

### ISSUE THREAD

**Issue by leandromac** [Roger-Melo/controle-de-despesas#2]
Olá Roger, estou seguindo o seu tutorial no youtube, e travei no minuto 12, quando é interpolado os elementos dentro do innerHTML.
Segui tudo conforme o tutorial, porém não é exibido o erro `Uncaught SyntaxError: Invalid or unexpected token`.
Pode me dizer o que estou fazendo de errado?
Segue meu repositório: https://github.com/leandromac/controle-financeiro

Obrigado e parabéns pelos vídeos!

**Comment by leandromac** [comment]
Consegui resolver o problema anterior.
Porém notei que não consigo usar a interpolação ` innerHTML = '${transaction.id}' ` O que fica dentro d interpolação, não é interpretado, sempre é impresso como string.
Eu fiz usando a concatenação ` innerHTML = 'string' + transaction.id + 'string' `, mas queria saber porque não estou conseguindo usar interpolando. ='(

**Comment by Roger-Melo** [comment]
Oi @leandromac.

Conseguiu resolver?

**Comment by leandromac** [comment]
Olá Roger, consegui sim.
Eu havia colocado o sinal de  **'**  onde na verdade era o sinal de **`** .
Obrigado e estou curtindo muito os seus vídeos, parabéns! ;)

**Comment by Roger-Melo** [comment]
@leandromac Show! No que precisar é só dar o toque =)
