### ISSUE TITLE
Exercício financeiro 

### ISSUE THREAD

**Issue by gustavonobreza** [Roger-Melo/controle-de-despesas#3]

**Comment by Roger-Melo** [comment]
Oi Gustavo. Está com alguma dúvida?

@Gustavonobreza

**Comment by gustavonobreza** [comment]
> Oi Gustavo. Está com alguma dúvida?
> 
> @Gustavonobreza 
> 

Nada não😬
Ainda tô aprendendo a usar o GitHub.
Mas obrigado pela atenção...
A propósito qual sua configuração do VsCode? O sr usa aquela extensão de Sync com o GitHub, pra nós conseguirmos ver...

**Comment by Roger-Melo** [comment]
Legal! Bem-vindo ao GitHub =D

Meu tema de cores é o One Dark (Sublime Babel) - que é uma extensão, com o background em #15202B.

As extensões são:

- Bracket Pair Colorizer
- Colorize
- Live Server
- VSCode Great Icons

@Gustavonobreza
